#!/bin/sh /etc/rc.common
# fzs-sms —— 短信轮询守护服务
USE_PROCD=1
START=95

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/fzs-smsd
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
